export interface ProductLastVisited {
    id                      : number,
    precio                  : number,
    publicacion             : string[],
    nombre                  : string,
    marca                   : string,
    descripcion             : any,
    detalles                : any,
    peso                    : any,
    ancho                   : any,
    alto                    : any,
    largo                   : any,
    imagen                  : string,
    elementos_recomendados  : number,
    fecha_registro          : string,
    sku                     : string,
    activo                  : number,
    convertida              : number,
    unique_id               : string,
    marca_autoparte         : number,
    subsubcategoria         : number
}